[package]
name = "demo-app"
version = "1.0.0"
edition = "2021"

[dependencies]

# Base de données : sqlite (défaut) | postgres | mysql | mariadb | all-databases
rusti = { path = "../../rusti", features = ["orm", "postgres"] }
serde.workspace = true

sea-orm-migration.workspace = true