[package]
name = "demo-app"
version = "1.0.0"
edition = "2021"

[dependencies]

# Base de données : sqlite (défaut) | postgres | mysql | mariadb | all-databases
runique = { version = "1.0.8", features = ["orm", "postgres"] }
serde ="1"

chrono = "0.4"
tracing-subscriber.workspace = true
