name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: github.repository_owner != 'actions'

    steps:
      - uses: actions/checkout@v4

      - name: Compute runique commit hash
        run: |
          echo "RUNIQUE_HASH=$(git rev-list -n 1 HEAD -- runique)" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Security Audit
        run: |
          cargo audit \
            --ignore RUSTSEC-2023-0071 \
            --ignore RUSTSEC-2025-0052 \
            --ignore RUSTSEC-2024-0384
        working-directory: runique

